### PR TITLE
Remove legacy json-sql lib

### PR DESCRIPTION
**Pull request by adamant-al**
- Removed legacy `json-sql` lib dir
- Used latest `json-sql` version
- Added workaround for `insertorupdate`
- Added workaround for `$upper`

To do:
- Use our fork https://github.com/Adamant-im/json-sql
- Add support in our fork for `insertorupdate` and `$upper` for postgre, based on old version (`json-sql` lib dir)
- Resolve other issues, if any

### CODE REVIEW

**Comment by adamant-al** [comment]
@martiliones Check the task

**Comment by adamant-al** [comment]
@yoxira 

Deploy the update on ahead using a blockchain image.

**Comment by yoxira** [comment]
I was merged with #82 and is running on the ahead node.

**Comment by bludnic** [comment]
Is this PR a duplicate of #82? Can it be closed? @yoxira

**Comment by yoxira** [comment]
@bludnic it can be closed.

**Pull request closed without merging**
